{
    'name': 'Attendance Quick Link',
    'version': '19.0.1.2.0',
    'author': 'Lógica Consultores 360',
    'website': 'https://www.logicaconsultores.com/',
    'summary': 'Fichaje por URL única por empleado, sin selección manual',
    'category': 'Human Resources/Attendances',
    'depends': ['hr', 'hr_attendance', 'hr_holidays', 'mail'],
    'data': [
        'data/ir_cron.xml',
        'data/mail_templates.xml',
        'views/hr_employee_views.xml',
        'views/hr_attendance_geo_inherit.xml',
        'views/hr_leave_type_inherit.xml',
        'views/res_config_settings_views.xml',
        'views/attendance_report_wizard_views.xml',
        'views/templates.xml',
        'views/hr_leave_calendar_inherit.xml',
    ],
    'post_init_hook': '_generate_tokens',
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'sequence': -1111,
    'license': 'LGPL-3',
    'price': 49.99,
    'currency': 'EUR',
}