{
    'name': 'Attendance Quick Link',
    'version': '19.0.2.1.0',
    'author': 'Lógica Consultores 360',
    'website': 'https://www.logicaconsultores.com',
    'summary': 'App de fichaje por enlace personal: fichar, calendario, ausencias y correcciones con aprobación de RRHH',
    'category': 'Human Resources/Attendances',
    'depends': ['web', 'hr', 'hr_attendance', 'hr_holidays', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/attendance_quicklink_security.xml',
        'data/ir_cron.xml',
        'data/mail_templates.xml',
        'views/hr_employee_views.xml',
        'views/hr_attendance_geo_inherit.xml',
        'views/hr_leave_type_inherit.xml',
        'views/res_config_settings_views.xml',
        'views/attendance_report_wizard_views.xml',
        'views/attendance_correction_request_views.xml',
        'views/templates.xml',
        'views/hr_leave_calendar_inherit.xml',
    ],
    'assets': {
        'attendance_quicklink.assets_app': [
            ('include', 'web._assets_core'),
            ('remove', 'web/static/src/core/**/*.scss'),
            'attendance_quicklink/static/src/scss/fonts.scss',
            'attendance_quicklink/static/src/scss/tokens.scss',
            'attendance_quicklink/static/src/app/**/*',
        ],
        'attendance_quicklink.assets_review': [
            'attendance_quicklink/static/src/scss/fonts.scss',
            'attendance_quicklink/static/src/scss/tokens.scss',
            'attendance_quicklink/static/src/scss/review.scss',
        ],
    },
    'post_init_hook': '_generate_tokens',
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'sequence': -111,
    'license': 'LGPL-3',
    'price': 20.00,
    'currency': 'EUR',
}
